spring:
  application:
    name: ice-gate
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #拦截所有api 打头的请求都经过zuul路由
  routes:  #路由表定义
    user-center:
      path: /uc/**
      serviceId: user-center
      #stripPrefix:false #不移除前缀
    auth-server:
      path: /auth/**
      serviceId: ice-auth
    product-server:
      path: /product/**
      serviceId: product-center
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
server:
  port: 8765

ribbon:
  eureka

jwt:
  token-header: Authorization
  pub-key:
    path: /Users/bingwu/Downloads/ice-gate/ice-zuul/src/main/resources/jwt/pub.key

client:
  id: ice-gate
  secret: 123456
  token-header: client-header
  pub-key:
    path: /Users/bingwu/Downloads/ice-gate/ice-zuul/src/main/resources/client/pub.key

gate:
  ignore:
    startWith: /static,/auth/jwt



