spring:
  application:
    name: ice-auth
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  basepackage: com.cssrc.auth.mapper
  xmlLocation: classpath:mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
server:
  port: 7777


jwt:
  expire: 3600
  pri-key:
    path: /Users/bingwu/Downloads/ice-gate/ice-auth/src/main/resources/jwt/pri.key
  pub-key:
    path: /Users/bingwu/Downloads/ice-gate/ice-auth/src/main/resources/jwt/pub.key

client:
  expire: 3600
  pri-key:
    path: /Users/bingwu/Downloads/ice-gate/ice-auth/src/main/resources/client/pri.key
  pub-key:
    path: /Users/bingwu/Downloads/ice-gate/ice-auth/src/main/resources/client/pub.key





